In [37]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree

In [38]:
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = np.array(data)
print(values)
# integer encode
integer_encoded = LabelEncoder().fit_transform(values)
print(integer_encoded)
# binary encode
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [45]:
def Encode(data):
    values = np.array(data)
    integer_encoded = LabelEncoder().fit_transform(values)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoder = OneHotEncoder(sparse=False)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    return onehot_encoded
data = pd.read_excel('C:/Users/Dell/Desktop/data.xlsx')
Age = data['Age']
Age = Encode(Age)
Age = pd.DataFrame(Age, columns = ['Age_1', 'Age_2', 'Age_3'])
print(Age)
Incoming = data['Incoming']
Incoming = Encode(Incoming)
Incoming = pd.DataFrame(Incoming, columns = ['Incoming_1', 'Incoming_2', 'Incoming_3'])
print(Incoming)
Student = data['Student']
Student = Encode(Student)
Student = pd.DataFrame(Student, columns = ['Student_1', 'Student_2'])
print(Student)
Credit = data['Credit Rating']
Credit = Encode(Credit)
Credit = pd.DataFrame(Credit, columns = ['Credit_1', 'Credit_2'])
print(Credit)
Buying = data['Buying']
Buying = np.array(Buying)
Buying = LabelEncoder().fit_transform(Buying)
Buying = pd.DataFrame(Buying, columns = ['Buying'])
print(Buying)

    Age_1  Age_2  Age_3
0     1.0    0.0    0.0
1     1.0    0.0    0.0
2     0.0    0.0    1.0
3     0.0    1.0    0.0
4     0.0    1.0    0.0
5     0.0    1.0    0.0
6     0.0    0.0    1.0
7     1.0    0.0    0.0
8     1.0    0.0    0.0
9     0.0    1.0    0.0
10    1.0    0.0    0.0
11    0.0    0.0    1.0
12    0.0    0.0    1.0
    Incoming_1  Incoming_2  Incoming_3
0          1.0         0.0         0.0
1          1.0         0.0         0.0
2          1.0         0.0         0.0
3          0.0         0.0         1.0
4          0.0         1.0         0.0
5          0.0         1.0         0.0
6          0.0         1.0         0.0
7          0.0         0.0         1.0
8          0.0         1.0         0.0
9          0.0         0.0         1.0
10         0.0         0.0         1.0
11         0.0         0.0         1.0
12         1.0         0.0         0.0
    Student_1  Student_2
0         1.0        0.0
1         1.0        0.0
2         1.0        0.0
3         1.0     

In [49]:
df = pd.concat([data[['User id']], Age, Incoming, Student, Credit, Buying], axis = 1)
df

User id  Age_1  Age_2  Age_3  Incoming_1  Incoming_2  Incoming_3  \
0         1    1.0    0.0    0.0         1.0         0.0         0.0   
1         2    1.0    0.0    0.0         1.0         0.0         0.0   
2         3    0.0    0.0    1.0         1.0         0.0         0.0   
3         4    0.0    1.0    0.0         0.0         0.0         1.0   
4         5    0.0    1.0    0.0         0.0         1.0         0.0   
5         6    0.0    1.0    0.0         0.0         1.0         0.0   
6         7    0.0    0.0    1.0         0.0         1.0         0.0   
7         8    1.0    0.0    0.0         0.0         0.0         1.0   
8         9    1.0    0.0    0.0         0.0         1.0         0.0   
9        10    0.0    1.0    0.0         0.0         0.0         1.0   
10       11    1.0    0.0    0.0         0.0         0.0         1.0   
11       12    0.0    0.0    1.0         0.0         0.0         1.0   
12       13    0.0    0.0    1.0         1.0         0.0         0.0   

    Student_1  Student_2  Credit_1  Credit_2  Buying  
0         1.0        0.0       0.0       1.0       0  
1         1.0        0.0       1.0       0.0       0  
2         1.0        0.0       0.0       1.0       1  
3         1.0        0.0       0.0       1.0       1  
4         0.0        1.0       0.0       1.0       1  
5         0.0        1.0       1.0       0.0       0  
6         0.0        1.0       1.0       0.0       1  
7         1.0        0.0       0.0       1.0       0  
8         0.0        1.0       0.0       1.0       1  
9         0.0        1.0       0.0       1.0       1  
10        0.0        1.0       1.0       0.0       1  
11        1.0        0.0       1.0       0.0       1  
12        0.0        1.0       0.0       1.0       1

In [56]:
X = df.iloc[:, 1:11]
X = np.array(X)
print(X)
Y = df['Buying']
Y = np.array(Y)
print(Y)
clf = tree.DecisionTreeClassifier()
clf.fit(X, Y)
clf.score(X, Y)

[[1. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 1.]]
[0 0 1 1 1 0 1 0 1 1 1 1 1]


1.0

In [58]:
clf.predict([[0,1,0,0,0,1,1,0,1,0]])

array([1])